name: Deploy Docker Image to Server

on:
  push:
    branches:
      - main  # Executa o deploy ao dar push no branch main
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - run: echo "O Job foi automaticamente disparado por  ${{ github.event_name }}"
    - run: echo "O Job esta rodando ${{ runner.os }} server"
    - run: echo "A Branch é ${{ github.ref }} e o repositorio é ${{ github.repository }}
    # Etapa 1: Checkout do código
    - name: Check out the repository
      uses: actions/checkout@v3

    # Etapa 2: Configurar SSH
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    # Etapa 3: Construir a imagem Docker
    - name: Build Docker image
      run: |
        docker build -t rodrigovollo/aula-fatec:my-python-app .
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Etapa 4: Copiar a imagem Docker para o servidor remoto
    - name: Push 
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/aula-fatec:my-python-app

    # Etapa 4.1: Parar conteniers
    - name: Run Docker container on server
      run: |
        ssh -o StrictHostKeyChecking=no aluno@201.23.3.86 'docker remove my-python-app --force'

    # Etapa 5: Rodar o container no servidor remoto
    - name: Run Docker container on server
      run: |
        ssh -o StrictHostKeyChecking=no aluno@201.23.3.86 'docker run --name my-python-app -d -p 80:80 ${{ secrets.DOCKER_USERNAME }}/aula-fatec:my-python-app'
